// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDienThoai.Models;

#nullable disable

namespace WebDienThoai.Migrations
{
    [DbContext(typeof(DatabaseTheKingContext))]
    [Migration("20251217054930_Hung")]
    partial class Hung
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebDienThoai.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("PK__Category__3213E83FE65758FB");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apple",
                            Slug = "apple"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Samsung",
                            Slug = "samsung"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Xiaomi",
                            Slug = "xiaomi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Phụ Kiện",
                            Slug = "phu-kien"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tai Nghe",
                            Slug = "tai-nghe"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ốp Lưng",
                            Slug = "op-lung"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dây Sạc",
                            Slug = "day-sac"
                        });
                });

            modelBuilder.Entity("WebDienThoai.Models.Inventory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("QuantityInStock")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ProductId")
                        .HasName("PK__Inventor__B40CC6CD941DC666");

                    b.ToTable("Inventory", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            QuantityInStock = 50
                        },
                        new
                        {
                            ProductId = 2,
                            QuantityInStock = 20
                        },
                        new
                        {
                            ProductId = 3,
                            QuantityInStock = 15
                        },
                        new
                        {
                            ProductId = 4,
                            QuantityInStock = 100
                        },
                        new
                        {
                            ProductId = 5,
                            QuantityInStock = 5
                        },
                        new
                        {
                            ProductId = 6,
                            QuantityInStock = 30
                        },
                        new
                        {
                            ProductId = 7,
                            QuantityInStock = 200
                        },
                        new
                        {
                            ProductId = 8,
                            QuantityInStock = 500
                        },
                        new
                        {
                            ProductId = 9,
                            QuantityInStock = 300
                        },
                        new
                        {
                            ProductId = 10,
                            QuantityInStock = 150
                        });
                });

            modelBuilder.Entity("WebDienThoai.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Orderdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("orderdate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Paymentstatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chưa thanh toán")
                        .HasColumnName("paymentstatus");

                    b.Property<string>("Shipaddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("shipaddress");

                    b.Property<string>("Shipname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("shipname");

                    b.Property<string>("Shipphone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("shipphone");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chờ xử lý")
                        .HasColumnName("status");

                    b.Property<decimal>("Totalprice")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("totalprice");

                    b.Property<int>("Userid")
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("PK__Order__3213E83F67510456");

                    b.HasIndex("Userid");

                    b.ToTable("Order", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Orderdate = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paymentstatus = "Chưa thanh toán",
                            Shipaddress = "123 Lê Lợi, Q1, HCM",
                            Shipname = "Nguyễn Văn A",
                            Shipphone = "0909123456",
                            Status = "Đang xử lý",
                            Totalprice = 33080000m,
                            Userid = 2
                        },
                        new
                        {
                            Id = 2,
                            Orderdate = new DateTime(2023, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Paymentstatus = "Đã thanh toán",
                            Shipaddress = "456 Nguyễn Huệ, Q1, HCM",
                            Shipname = "Trần Thị B",
                            Shipphone = "0912345678",
                            Status = "Đã giao",
                            Totalprice = 5490000m,
                            Userid = 3
                        });
                });

            modelBuilder.Entity("WebDienThoai.Models.OrderItem", b =>
                {
                    b.Property<int>("Orderid")
                        .HasColumnType("int")
                        .HasColumnName("orderid");

                    b.Property<int>("Productid")
                        .HasColumnType("int")
                        .HasColumnName("productid");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Unitprice")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("unitprice");

                    b.HasKey("Orderid", "Productid")
                        .HasName("PK__OrderIte__3ADF45A617256A6F");

                    b.HasIndex("Productid");

                    b.ToTable("OrderItem", (string)null);

                    b.HasData(
                        new
                        {
                            Orderid = 1,
                            Productid = 1,
                            Quantity = 1,
                            Unitprice = 27590000m
                        },
                        new
                        {
                            Orderid = 1,
                            Productid = 7,
                            Quantity = 1,
                            Unitprice = 5490000m
                        },
                        new
                        {
                            Orderid = 2,
                            Productid = 7,
                            Quantity = 1,
                            Unitprice = 5490000m
                        });
                });

            modelBuilder.Entity("WebDienThoai.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoryid")
                        .HasColumnType("int")
                        .HasColumnName("categoryid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("imageUrl");

                    b.Property<bool>("IsOnSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isOnSale");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isPublished");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("price");

                    b.Property<decimal?>("Saleprice")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("saleprice");

                    b.HasKey("Id")
                        .HasName("PK__Product__3213E83FB57B5FD7");

                    b.HasIndex("Categoryid");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoryid = 1,
                            Description = "Titanium, Chip A17 Pro mạnh mẽ.",
                            ImageUrl = "/img/10.jpg",
                            IsOnSale = true,
                            IsPublished = true,
                            Name = "iPhone 15 Pro",
                            Price = 28990000m,
                            Saleprice = 27590000m
                        },
                        new
                        {
                            Id = 2,
                            Categoryid = 2,
                            Description = "Camera AI đột phá, màn hình Dynamic AMOLED 2X.",
                            ImageUrl = "/img/20.jpg",
                            IsOnSale = false,
                            IsPublished = true,
                            Name = "Samsung S25",
                            Price = 27500000m,
                            Saleprice = 27500000m
                        },
                        new
                        {
                            Id = 3,
                            Categoryid = 1,
                            Description = "Thiết kế bền bỉ, Camera kép tiên tiến.",
                            ImageUrl = "/img/9.jpg",
                            IsOnSale = false,
                            IsPublished = true,
                            Name = "Iphone 13",
                            Price = 22990000m,
                            Saleprice = 22990000m
                        },
                        new
                        {
                            Id = 4,
                            Categoryid = 1,
                            Description = "Pin trâu, hiệu năng ổn định.",
                            ImageUrl = "/img/19.jpg",
                            IsOnSale = true,
                            IsPublished = true,
                            Name = "iPhone 14",
                            Price = 13790000m,
                            Saleprice = 12990000m
                        },
                        new
                        {
                            Id = 5,
                            Categoryid = 1,
                            Description = "Công nghệ tương lai, thiết kế siêu mỏng.",
                            ImageUrl = "/img/iphone-17.jpg",
                            IsOnSale = false,
                            IsPublished = true,
                            Name = "iPhone 17",
                            Price = 34990000m,
                            Saleprice = 34990000m
                        },
                        new
                        {
                            Id = 6,
                            Categoryid = 3,
                            Description = "Hợp tác cùng Leica, nhiếp ảnh đỉnh cao.",
                            ImageUrl = "/img/17.jpg",
                            IsOnSale = false,
                            IsPublished = true,
                            Name = "Xiaomi 14 Ultra",
                            Price = 21990000m,
                            Saleprice = 21990000m
                        },
                        new
                        {
                            Id = 7,
                            Categoryid = 5,
                            Description = "Chống ồn chủ động, âm thanh không gian.",
                            ImageUrl = "/img/14.jpg",
                            IsOnSale = true,
                            IsPublished = true,
                            Name = "AirPods Pro 2",
                            Price = 6190000m,
                            Saleprice = 5490000m
                        },
                        new
                        {
                            Id = 8,
                            Categoryid = 6,
                            Description = "Chống sốc chuẩn quân đội.",
                            ImageUrl = "/img/22.jpg",
                            IsOnSale = false,
                            IsPublished = true,
                            Name = "Ốp lưng Spigen",
                            Price = 750000m,
                            Saleprice = 750000m
                        },
                        new
                        {
                            Id = 9,
                            Categoryid = 7,
                            Description = "Siêu bền, hỗ trợ sạc nhanh 100W.",
                            ImageUrl = "/img/26.jpg",
                            IsOnSale = false,
                            IsPublished = true,
                            Name = "Cáp Type C Anker",
                            Price = 350000m,
                            Saleprice = 350000m
                        },
                        new
                        {
                            Id = 10,
                            Categoryid = 6,
                            Description = "Trong suốt, không ố vàng.",
                            ImageUrl = "/img/21.jpg",
                            IsOnSale = false,
                            IsPublished = true,
                            Name = "Ốp lưng iPhone 15",
                            Price = 450000m,
                            Saleprice = 450000m
                        });
                });

            modelBuilder.Entity("WebDienThoai.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("fullname");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Customer")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PK__User__3213E83FC1F34C1D");

                    b.HasIndex(new[] { "Email" }, "UQ__User__AB6E616496D0E9A7")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ__User__F3DBC57208F9FBAD")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@theking.vn",
                            Fullname = "Quản Trị Viên",
                            Passwordhash = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "khachhang@gmail.com",
                            Fullname = "Nguyễn Văn A",
                            Passwordhash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Role = "Customer",
                            Username = "khachhang"
                        },
                        new
                        {
                            Id = 3,
                            Email = "tranthib@gmail.com",
                            Fullname = "Trần Thị B",
                            Passwordhash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Role = "Customer",
                            Username = "khachhang2"
                        });
                });

            modelBuilder.Entity("WebDienThoai.Models.Inventory", b =>
                {
                    b.HasOne("WebDienThoai.Models.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("WebDienThoai.Models.Inventory", "ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Produ__440B1D61");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebDienThoai.Models.Order", b =>
                {
                    b.HasOne("WebDienThoai.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("Userid")
                        .IsRequired()
                        .HasConstraintName("FK__Order__userid__49C3F6B7");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebDienThoai.Models.OrderItem", b =>
                {
                    b.HasOne("WebDienThoai.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("Orderid")
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__order__4CA06362");

                    b.HasOne("WebDienThoai.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("Productid")
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__produ__4D94879B");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebDienThoai.Models.Product", b =>
                {
                    b.HasOne("WebDienThoai.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("Categoryid")
                        .IsRequired()
                        .HasConstraintName("FK__Product__categor__403A8C7D");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebDienThoai.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebDienThoai.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("WebDienThoai.Models.Product", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("WebDienThoai.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
